spring.application.name=shorex-backend

spring.datasource.url=jdbc:mysql://localhost:3306/shorex_esports
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=shorexEsportsSecretKeyForJwtToken123456789ShorexSecureAdminKey2026
jwt.expiration=86400000

FRONTEND_URL=http://localhost:3000

server.port=8081